export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"

export const GET_ORDER_CUS_REQUEST = "GET_ORDER_CUS_REQUEST"
export const GET_ORDER_CUS_SUCCESS = "GET_ORDER_CUS_SUCCESS"
export const GET_ORDER_CUS_FAIL = "GET_ORDER_CUS_FAIL"